name = "cours-arabe-3eme"
compatibility_date = "2024-10-01"
pages_build_output_dir = "apps/web/dist"

[build]
command = "npm ci && npm -w apps/web run build"

[[d1_databases]]
binding = "DB"
database_name = "cours_arabe_3eme"
database_id = "cf44927c-8105-43d8-8701-3fb9413ceab1"
